---
# Demo server for purkinje test runner
# Prerequisite:
# Role "common" (https://github.com/bbiskup/ansible-serverconfig)

- include_vars: main.yml
- name: Create demo user
  user: >
      name={{purkinje_demo_user}}
      comment="Demo user for purkinje test runner"
      home="{{demo_home}}"

- name: Package management | APT update & upgrade
  apt: update_cache=yes upgrade=full
  when: refresh_apt

- name: Install prerequisite APT packages
  apt: name={{item}}
  with_items:
    - python
    - python-virtualenv
    - git
    - supervisor
    - nmap
    - python-dev
    - libyaml-dev

- name: Install demo test execution script
  template: >
    src=scripts/run_demo_tests.bash.j2
    dest={{demo_home}}/run_demo_tests.bash
    mode="540"
    owner={{purkinje_demo_user}}

- name: Create virtualenvs
  shell: >
    cd && (virtualenv {{item}} || echo "Could not create virtualenv {{item}}")
  sudo: yes
  sudo_user: "{{purkinje_demo_user}}"
  with_items:
   - "{{purkinje_venv_dir}}"
   - "{{sampleproject_venv_dir}}"

- name: Install purkinje
  shell: >
     . {{purkinje_venv_dir}}/bin/activate &&
     pip install --upgrade purkinje
  sudo_user: "{{purkinje_demo_user}}"

- name: Install purkinje configuration
  template: >
      src=conf/purkinje.yml
      dest={{demo_home}}/purkinje.yml
  sudo_user: "{{purkinje_demo_user}}"

- name: Create sample project directory
  file: >
      path={{demo_home}}/purkinje-sampleproject
      state=directory
  sudo_user: "{{purkinje_demo_user}}"

- name: Check out purkinje-sampleproject repository
  git: >
      repo=https://github.com/bbiskup/purkinje-sampleproject
      version=dev
      dest={{demo_home}}/purkinje-sampleproject
  sudo_user: "{{purkinje_demo_user}}"

- name: Install purkinje-sampleproject dependencies
  shell: >
    . {{sampleproject_venv_dir}}/bin/activate &&
    pip install --upgrade -r dev-requirements.txt
    chdir="{{demo_home}}/purkinje-sampleproject"
  sudo: yes
  sudo_user: "{{purkinje_demo_user}}"

#- name: Install pytest to run purkinje tests
#  shell: >
#      pip install pytest
#  sudo_user: "{{purkinje_demo_user}}"

- name: Configure supervisor to run demo server and tests
  template: >
    src=supervisor/purkinje_demo.conf.j2
    dest=/etc/supervisor/conf.d/purkinje_demo.conf
  notify:
    - restart supervisor
