---
# Demo server for purkinje test runner
# Prerequisite:
# Role "common" (https://github.com/bbiskup/ansible-serverconfig)

- include_vars: main.yml
- name: Create demo user
  user: >
      name={{purkinje_demo_user}}
      comment="Demo user for purkinje test runner"
      home="{{demo_home}}"

- name: Package management | APT update & upgrade
  apt: update_cache=yes upgrade=full
  when: refresh_apt

- name: Install prerequisite APT packages
  apt: name={{item}}
  with_items:
    - python
    - nodejs
    - npm

# bower hashbang references 'node' nodejs
- name: Create nodejs link for bower
  file: >
    src=/usr/bin/nodejs 
    dest=/usr/bin/node 
    state="link"

- name: Create virtualenv
  shell: virtualenv {{venv_dir}}
  sudo: yes
  sudo_user: "{{purkinje_demo_user}}"

- name: Clone git repositories
  git: >
    repo="git://github.com/bbiskup/{{item}}.git"
    accept_hostkey=yes
    dest="{{demo_home}}/{{item}}"
  with_items:
    - flotsam
    - purkinje-messages
    - pytest-purkinje
    - purkinje
    - purkinje-sampleproject
  sudo: yes
  sudo_user: "{{purkinje_demo_user}}"

- name: Install flotsam
  shell: >
     . {{venv_dir}}/bin/activate &&
     pip install -r requirements.txt &&
     pip install -e .
     chdir="{{demo_home}}/flotsam"
  sudo: yes
  sudo_user: "{{purkinje_demo_user}}"

- name: Install purkinje-messages
  shell: >
     . {{venv_dir}}/bin/activate &&
     pip install -r requirements.txt &&
     pip install -e .
     chdir="{{demo_home}}/purkinje-messages"
  sudo: yes
  sudo_user: "{{purkinje_demo_user}}"

- name: Install pytest-purkinje
  shell: >
     . {{venv_dir}}/bin/activate &&
     pip install -r requirements.txt &&
     pip install -e .
     chdir="{{demo_home}}/pytest-purkinje"
  sudo: yes
  sudo_user: "{{purkinje_demo_user}}"

# TODO: should not be needed in production;
# build assets and include them in egg
- name: Install bower
  shell: >
     npm install -g bower

- name: Install purkinje
  shell: >
     . {{venv_dir}}/bin/activate &&
     pip install -r requirements.txt &&
     npm install &&
     bower install --production --force-latest &&
     bower install angular --force-latest &&
     pip install -e .
     chdir="{{demo_home}}/purkinje"
  sudo: yes
  sudo_user: "{{purkinje_demo_user}}"

- name: Install purkinje-sampleproject
  shell: >
     . {{venv_dir}}/bin/activate &&
     pip install -r dev-requirements.txt
     chdir="{{demo_home}}/purkinje-sampleproject"
  sudo: yes
  sudo_user: "{{purkinje_demo_user}}"
