---
# Demo server for purkinje test runner
# Prerequisite:
# Role "common" (https://github.com/bbiskup/ansible-serverconfig)

- include_vars: main.yml
- name: Create demo user
  user: >
      name={{purkinje_demo_user}}
      comment="Demo user for purkinje test runner"
      home="{{demo_home}}"

- name: Package management | APT update & upgrade
  apt: update_cache=yes upgrade=full
  when: refresh_apt

- name: Install prerequisite APT packages
  apt: name={{item}}
  with_items:
    - python

- name: Create virtualenv
  shell: virtualenv {{venv_dir}}
  sudo: yes
  sudo_user: "{{purkinje_demo_user}}"

- name: Clone git repositories
  git: >
    repo="git://github.com/bbiskup/{{item}}.git"
    accept_hostkey=yes
    dest="{{demo_home}}/{{item}}"
  with_items:
    - flotsam
    - purkinje-messages
    - pytest-purkinje
    - purkinje
  sudo: yes
  sudo_user: "{{purkinje_demo_user}}"

- name: Install flotsam
  shell: >
     . {{venv_dir}}/bin/activate &&
     pip install -r requirements.txt &&
     pip install -e .
     chdir="{{demo_home}}/flotsam"
  sudo: yes
  sudo_user: "{{purkinje_demo_user}}"
